### ISSUE TITLE
Does not build in SBCL 2.0.9 - :type/:initform issue

### ISSUE THREAD

**Issue by quicklisp** [cldm/cl-semver#3]
I get this: `Constant NIL conflicts with its asserted type INTEGER.`

Full log here: http://report.quicklisp.org/2020-09-30/failure-report/cl-semver.html#cl-semver

**Comment by mmontone** [comment]
Thanks. I'll fix.

**Comment by mmontone** [comment]
I think it compiles fine now.

**Comment by quicklisp** [comment]
Looks good to me, thanks!
